# SwiftLint 配置文件
# 用于保持 ProjectManager 代码质量和一致性

# 包含的规则
opt_in_rules:
  - array_init
  - closure_spacing
  - collection_alignment
  - empty_count
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - last_where
  - let_var_whitespace
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - nimble_operator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_zero_over_explicit_init
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call

# 禁用的规则
disabled_rules:
  - trailing_whitespace # 由于注释可能包含中文，暂时禁用
  - identifier_name # 允许中文变量名和较短的变量名

# 包含的路径
included:
  - Sources
  - Tests

# 排除的路径
excluded:
  - .build
  - node_modules
  - .github
  - docs

# 自定义规则配置
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 400
  error: 500

function_body_length:
  warning: 50
  error: 80

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 300
  error: 400

cyclomatic_complexity:
  warning: 15
  error: 25

nesting:
  type_level:
    warning: 2
    error: 3

# 标识符命名
identifier_name:
  min_length:
    warning: 1
    error: 0
  max_length:
    warning: 50
    error: 60
  excluded:
    - id
    - x
    - y
    - z

type_name:
  min_length:
    warning: 3
    error: 1
  max_length:
    warning: 50
    error: 60

# 自定义规则
custom_rules:
  # 避免强制解包，鼓励安全的可选值处理
  avoid_force_unwrap:
    name: "避免强制解包"
    regex: '\!\s*\)'
    message: "避免使用强制解包，考虑使用可选绑定或 nil 合并操作符"
    severity: warning
    
  # 确保 TODO 注释包含描述
  todo_with_description:
    name: "TODO 需要描述"
    regex: '\/\/\s*TODO:'
    message: "TODO 注释应该包含具体的描述"
    severity: warning
    
  # 标签系统相关函数需要注释
  tag_function_documentation:
    name: "标签函数文档"
    regex: 'func.*tag.*\{'
    message: "涉及标签系统的函数应该包含详细注释，说明数据安全注意事项"
    severity: warning

# 报告格式
reporter: "xcode"